# Generated by Django 3.0 on 2022-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moverspackers', '0003_siteuser_shiftingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='isread',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
